version: '3'
services:
   node:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
      - ./:/app
     command: sh -c "cd react-sample && yarn start"
     ports:
      - "3000:3000"
